version: '3.7'

services:
    app:
        pull_policy: build
        build: ./
        command: ls
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: yourstreamlitapp:latest
