services:
    app:
        pull_policy: build
        build: ./
        command: >
            bash -c "python -V
            &&  streamlit run app/main.py --server.port 8502 --server.address=0.0.0.0"
        volumes:
            - ./:/usr/src/app
        ports:
            - 8502:8502
        image: yourstreamlitapp:latest
    app2:
        pull_policy: build
        build: ./
        command: >
            bash -c "python -V
            &&  streamlit run app/main.py --server.port 8503 --server.address=0.0.0.0"
        volumes:
            - ./:/usr/src/app
        ports:
            - 8503:8503
        image: yourstreamlitapp:latest
